version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      androidx:
        patterns:
          - "androidx*"
          - "com.android*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
