package com.ganesh.hisabkitabpro.domain.businesscard

/**
 * Top-level aesthetic family. Each category gets exactly 10 procedural blueprints,
 * yielding the 50-card master sheet generated by [MultiTemplateGenerator].
 */
enum class BusinessCardCategory(
    val displayName: String,
    val tagline: String,
) {
    ROYAL_SIGNATURE(
        displayName = "Royal Signature",
        tagline = "Amoled black + metallic gold",
    ),
    CORPORATE_ELITE(
        displayName = "Corporate Elite",
        tagline = "Minimalist, high-contrast, generous negative space",
    ),
    MODERN_ABSTRACT(
        displayName = "Modern Abstract",
        tagline = "Procedural geometry — no external assets",
    ),
    ECO_ORGANIC(
        displayName = "Eco Organic",
        tagline = "Matte, grained, paper-soft palettes",
    ),
    DIGITAL_NATIVE(
        displayName = "Digital Native",
        tagline = "Glow accents, neon hairlines, tech borders",
    ),
}
