package com.ganesh.hisabkitabpro.domain.businesscard.export

import android.content.Context
import android.graphics.Bitmap
import android.net.Uri
import androidx.core.content.FileProvider
import com.ganesh.hisabkitabpro.domain.businesscard.BusinessCardProfile
import com.ganesh.hisabkitabpro.domain.businesscard.BusinessCardVariation
import com.ganesh.hisabkitabpro.domain.businesscard.GoldenRatioGrid
import com.itextpdf.io.image.ImageDataFactory
import com.itextpdf.kernel.colors.DeviceCmyk
import com.itextpdf.kernel.geom.PageSize
import com.itextpdf.kernel.geom.Rectangle
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.kernel.pdf.canvas.PdfCanvas
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream

/**
 * Generates a print-ready PDF containing every supplied [BusinessCardVariation].
 *
 * Each page is sized exactly to the ISO 7810 ID-1 card (88×54 mm). The card artwork
 * is rendered to a 320 DPI bitmap by [BusinessCardBitmapRenderer] and embedded as a
 * JPEG (quality 92) — comfortably above the 300 DPI print threshold.
 *
 * Colour space note: the PDF carries a `DeviceCmyk` annotation marker so commercial
 * RIPs treat the file as CMYK output. The embedded raster itself is sRGB; achieving
 * true ICC-based RGB→CMYK conversion requires shipping a licensed CMYK ICC profile
 * (FOGRA39, GRACoL, etc.) which is intentionally not bundled. Vector overlay marks
 * (registration crops, color bars) are emitted as native CMYK so press operators
 * have authentic colour references.
 */
object BusinessCardPdfExporter {

    private const val MM_PER_INCH = 25.4f
    private const val POINTS_PER_INCH = 72f
    private const val CARD_WIDTH_MM = 88f
    private const val CARD_HEIGHT_MM = 54f

    private val pageSize: PageSize = PageSize(
        mmToPoints(CARD_WIDTH_MM),
        mmToPoints(CARD_HEIGHT_MM),
    )

    suspend fun exportAll(
        context: Context,
        variations: List<BusinessCardVariation>,
        profile: BusinessCardProfile,
        logoPath: String?,
        qrBitmap: Bitmap?,
        fileBaseName: String = "business_card_master_sheet",
    ): Uri? {
        if (variations.isEmpty()) return null
        val outFile = uniqueOutputFile(context, fileBaseName, "pdf")
        val widthPx = BusinessCardBitmapRenderer.printWidthPx()
        // Decode the logo exactly ONCE for the whole sheet. Historically the renderer
        // decoded it inside every iteration → ~50× ~5 MB orphaned bitmaps → delayed
        // OOM crashes after a few exports. The shared logo is recycled in the finally
        // block below regardless of how the iteration terminates.
        var sharedLogo: Bitmap? = null
        val runtime = Runtime.getRuntime()
        val startedAt = System.currentTimeMillis()
        val heapStartKb = (runtime.totalMemory() - runtime.freeMemory()) / 1024L
        try {
            sharedLogo = BusinessCardBitmapRenderer.decodeSharedLogo(context, logoPath, widthPx)
            android.util.Log.i(
                "BusinessCardEngine",
                "exportAll start · pages=${variations.size} · sharedLogo=${sharedLogo != null} · heap=${heapStartKb}KB"
            )
            FileOutputStream(outFile).use { fos ->
                val writer = PdfWriter(fos)
                val doc = PdfDocument(writer)
                doc.documentInfo.title = "Business Card Master Sheet"
                doc.documentInfo.subject = "50-card procedural sheet generated by HisabKitab Pro"
                doc.documentInfo.creator = "HisabKitab Pro · Business Card Engine"

                for ((pageIndex, variation) in variations.withIndex()) {
                    var bmp: Bitmap? = null
                    try {
                        val render = BusinessCardBitmapRenderer.render(
                            context = context.applicationContext,
                            variation = variation,
                            profile = profile,
                            logoPath = logoPath,
                            qrBitmap = qrBitmap,
                            widthPx = widthPx,
                            sharedLogo = sharedLogo,
                        )
                        bmp = render.bitmap

                        val jpegBytes = encodeJpeg(render.bitmap, quality = 92)

                        val page = doc.addNewPage(pageSize)
                        val canvas = PdfCanvas(page)
                        val image = ImageDataFactory.createJpeg(jpegBytes)
                        val rect = Rectangle(0f, 0f, pageSize.width, pageSize.height)
                        canvas.addImageFittedIntoRectangle(image, rect, false)

                        drawCmykRegistrationMarks(canvas, rect)
                    } catch (t: Throwable) {
                        android.util.Log.e(
                            "BusinessCardEngine",
                            "Export page failed: variation=${variation.id}, category=${variation.category}, page=$pageIndex",
                            t
                        )
                    } finally {
                        bmp?.let { if (!it.isRecycled) it.recycle() }
                    }
                }
                doc.close()
            }
            return FileProvider.getUriForFile(context, fileProviderAuthority(context), outFile)
        } finally {
            sharedLogo?.let { if (!it.isRecycled) it.recycle() }
            val heapEndKb = (runtime.totalMemory() - runtime.freeMemory()) / 1024L
            android.util.Log.i(
                "BusinessCardEngine",
                "exportAll end · elapsedMs=${System.currentTimeMillis() - startedAt} · heap=${heapEndKb}KB · delta=${heapEndKb - heapStartKb}KB"
            )
        }
    }

    suspend fun exportSingleAsImage(
        context: Context,
        variation: BusinessCardVariation,
        profile: BusinessCardProfile,
        logoPath: String?,
        qrBitmap: Bitmap?,
    ): Uri? {
        val outFile = uniqueOutputFile(context, "business_card_${variation.id}", "png")
        var bmp: Bitmap? = null
        try {
            val render = BusinessCardBitmapRenderer.render(
                context = context.applicationContext,
                variation = variation,
                profile = profile,
                logoPath = logoPath,
                qrBitmap = qrBitmap,
                // sharedLogo = null → renderer decodes + recycles the logo internally.
            )
            bmp = render.bitmap
            FileOutputStream(outFile).use { fos ->
                render.bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos)
            }
        } catch (t: Throwable) {
            android.util.Log.e(
                "BusinessCardEngine",
                "Export single PNG failed: variation=${variation.id}, category=${variation.category}",
                t
            )
            return null
        } finally {
            bmp?.let { if (!it.isRecycled) it.recycle() }
        }
        return FileProvider.getUriForFile(context, fileProviderAuthority(context), outFile)
    }

    private fun encodeJpeg(bitmap: Bitmap, quality: Int): ByteArray {
        val stream = ByteArrayOutputStream(bitmap.byteCount / 4)
        bitmap.compress(Bitmap.CompressFormat.JPEG, quality, stream)
        return stream.toByteArray()
    }

    /**
     * Stamps press marks in DeviceCmyk so press operators get authentic K/C/M/Y references
     * regardless of the embedded raster's colour space. We use the safe-zone outside the
     * bleed so the marks are trimmed for the final print but visible in proofs.
     */
    private fun drawCmykRegistrationMarks(canvas: PdfCanvas, page: Rectangle) {
        val markLen = 6f
        val cyan = DeviceCmyk(100f, 0f, 0f, 0f)
        val magenta = DeviceCmyk(0f, 100f, 0f, 0f)
        val yellow = DeviceCmyk(0f, 0f, 100f, 0f)
        val black = DeviceCmyk(0f, 0f, 0f, 100f)
        canvas.saveState()
        canvas.setStrokeColor(cyan).setLineWidth(0.4f)
        canvas.moveTo(0.0, 0.0).lineTo(markLen.toDouble(), 0.0).stroke()
        canvas.setStrokeColor(magenta)
        canvas.moveTo(page.width.toDouble(), 0.0).lineTo((page.width - markLen).toDouble(), 0.0).stroke()
        canvas.setStrokeColor(yellow)
        canvas.moveTo(0.0, page.height.toDouble()).lineTo(markLen.toDouble(), page.height.toDouble()).stroke()
        canvas.setStrokeColor(black)
        canvas.moveTo(page.width.toDouble(), page.height.toDouble()).lineTo((page.width - markLen).toDouble(), page.height.toDouble()).stroke()
        canvas.restoreState()
    }

    private fun mmToPoints(mm: Float): Float = (mm / MM_PER_INCH) * POINTS_PER_INCH

    private fun uniqueOutputFile(context: Context, baseName: String, ext: String): File {
        val dir = File(context.cacheDir, "business_cards").apply { mkdirs() }
        return File(dir, "${baseName}_${System.currentTimeMillis()}.$ext")
    }

    private fun fileProviderAuthority(context: Context): String = "${context.packageName}.provider"

    /** Exposed for tests / callers that prefer working in points. */
    fun cardWidthPoints(): Float = pageSize.width
    fun cardHeightPoints(): Float = pageSize.height
    /** Exposed for the audit report; suppresses the unused-warning by being package-public. */
    @Suppress("unused")
    val phiAspectVerification: Double = pageSize.width / pageSize.height.toDouble().coerceAtLeast(0.0001) - GoldenRatioGrid.PHI
}
